### ISSUE TITLE
Hello Hacktoberfest :)

### ISSUE THREAD

**Issue by MrBenJ** [MrBenJ/modern-js-by-example#2]
Hi! Thank you for taking the time to check out this issue.

I've created this guide to help other developers, new and seasoned, to see real-world examples of Javascript in today's world. 

I've finished up the book for the most part (you can see that in `/book`) and I'd love contributions to:

* Clean up any grammatical or spelling errors
* Add new examples
* Add new sections you feel would help other developers

I will be reviewing all PR's and encourage anyone to contribute to this book. I'm working on a website to automatically update and read all the markdown files in `/book`, but until then, this book will live on Github.

Thank you for contributing to open source software!

**Comment by jerodsanto** [comment]
Just a quick note that if you add a 'hacktoberfest' label to this issue it will (allegedly) get listed on their website so folks can stumble upon your repo. YMMV, of course :)

**Comment by MrBenJ** [comment]
Thanks @jerodsanto ! Done and done
