### ISSUE TITLE
potential typo

### ISSUE THREAD

**Issue by marwahaha** [MrBenJ/modern-js-by-example#77]
I noticed this line in Chapter 5:

> My personal preference is that all the content async functions, despite if async calls are happening or not should be wrapped in try/catch.

What is a `content async function`?

**Comment by MrBenJ** [comment]
That's definitely a typo. It should be:
> My personal preference is that all the content inside of async functions, despite if async calls are happening or not, should be wrapped in try/catch.

Probably could word it better too:
> My personal preferences is that all code running in an `async function` should be wrapped in `try/catch`, even if there aren't any async operations or API calls happening inside. 

Feel free to open up a PR with this fix 😄
